### ISSUE TITLE
Tests fail with Mojolicious 6.xx

### ISSUE THREAD

**Issue by eserte** [kanatohodets/mojo-useragent-unixsocket#1]
See http://analysis.cpantesters.org/solved?distv=Mojo-UserAgent-UnixSocket-0.021#mod%3AMojolicious for statistical analysis of test reports.

**Comment by kanatohodets** [comment]
yikes! didn't get back to you very quickly. anyway, Mojo supports this natively for... the past three years, so I'm archiving this repo. thank you so much for the work you do to keep quality in the Perl ecosystem high!
